// the user will give us a string and a number for the rotating amount
// we need to rotate the string as the number of rotate amount
// we will test if the number equal 0 or the given number equal the length of the string
// if these conditions are true then we will directly return the string as it is 
// if the rotate amount is less then the lenght of the string and superior to 0 
// then we will loop from 1 to the reapeat amount number ( if num =4 for (i=1;i<=4;i++))
// we will create a temporary variable that we will put inside it the last caractere of the string in each itiration 
// we will delete the the last caractere of the string 
// we will add the temporary variable to the string ( string=temp+string)
// we will retun the string 
// else if the repeated amount is higher than the length of the string 
// we will repeat the same loop but itration number will be repeat amount - length of the string 
// we will create a temporary variable that we will put inside it the last caractere of the string in each itiration 
// we will delete the the last caractere of the string 
// we will add the temporary variable to the string ( string=temp+string)
// we will retun the string 



/////

// the user will give us a string and a number for the rotating amount
// we need to rotate the string as the number of rotate amount
// we will test if the number equal 0 or the given number equal the length of the string
// if these conditions are true then we will directly return the string as it is 
// if the rotate amount is less then the lenght of the string and superior to 0




